locals {
  vpc_cidr = "172.16.0.0/16"
  azs      = slice(data.aws_availability_zones.available.names, 0, 3)
}

# Public subnets exist to host the internet-facing ALB samples (see samples/msk-akhq); the
# module's own map_public_ip_on_launch default is already false (auto-assign is off), and an
# internet-facing ALB gets its public IPs from the ELB service directly regardless of that
# subnet setting, so nothing here grants EC2 instances a public IP by default.
# kics-scan ignore-block
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "6.6.1"

  name = "vpc-aws-lab"
  cidr = local.vpc_cidr

  azs              = local.azs
  public_subnets   = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 8, k)]
  private_subnets  = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 4, k + 4)]
  database_subnets = [for k, v in local.azs : cidrsubnet(local.vpc_cidr, 8, k + 8)]

  enable_dns_hostnames = true
  enable_dns_support   = true

  enable_nat_gateway = false
  single_nat_gateway = false
  reuse_nat_ips      = false

  # Traceability control (referentiel_cybersecurite): every VPC ships with Flow Logs
  # enabled by default so network traffic is auditable; short retention keeps lab cost low.
  enable_flow_log                                 = true
  create_flow_log_cloudwatch_log_group            = true
  create_flow_log_cloudwatch_iam_role             = true
  flow_log_destination_type                       = "cloud-watch-logs"
  flow_log_traffic_type                           = "ALL"
  flow_log_cloudwatch_log_group_retention_in_days = 1
  flow_log_cloudwatch_log_group_kms_key_id        = aws_kms_key.logs.arn

  tags = local.tags
}

# KMS key used to encrypt CloudWatch Logs generated by this stack (VPC Flow Logs).
# Root-account administrator statement is the AWS-documented baseline for every KMS key
# policy (a key with no root grant can permanently lock the account out of its own key);
# kms:* is scoped to this account's root principal only, not a public/anonymous wildcard.
# kics-scan ignore-block
resource "aws_kms_key" "logs" {
  description         = "CMK for CloudWatch Logs encryption - ${local.name}"
  enable_key_rotation = true
  policy              = data.aws_iam_policy_document.logs_kms.json
  tags                = local.tags
}

resource "aws_kms_alias" "logs" {
  name          = "alias/${local.name}-logs"
  target_key_id = aws_kms_key.logs.key_id
}

data "aws_iam_policy_document" "logs_kms" {
  statement {
    sid       = "AllowRootAccountAdmin"
    effect    = "Allow"
    actions   = ["kms:*"]
    resources = ["*"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"]
    }
  }

  statement {
    sid    = "AllowCloudWatchLogs"
    effect = "Allow"
    actions = [
      "kms:Encrypt*",
      "kms:Decrypt*",
      "kms:ReEncrypt*",
      "kms:GenerateDataKey*",
      "kms:Describe*",
    ]
    resources = ["*"]

    principals {
      type        = "Service"
      identifiers = ["logs.${var.aws_region}.amazonaws.com"]
    }

    condition {
      test     = "ArnLike"
      variable = "kms:EncryptionContext:aws:logs:arn"
      values   = ["arn:aws:logs:${var.aws_region}:${data.aws_caller_identity.current.account_id}:*"]
    }
  }
}
